# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'fbProject' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for fbProject
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'


  target 'fbProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'fbProject-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for fbProject-tvOS

  target 'fbProject-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
